17-May-2024 17:05:34.786 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
17-May-2024 17:05:34.787 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
17-May-2024 17:05:34.789 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@5db4c359')
17-May-2024 17:13:58.195 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
17-May-2024 17:13:58.196 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
17-May-2024 17:13:58.197 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@47874b25')
17-May-2024 17:18:26.402 SEVERE [http-nio-8084-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet [org.bmbgarage.servlet.LoginServlet] lanzó excepción
	org.jdbi.v3.core.ConnectionException: java.sql.SQLException: ORA-01017: nombre de usuario/contraseña no válidos; conexión denegada

https://docs.oracle.com/error-help/db/ora-01017/
		at org.jdbi.v3.core.Jdbi.open(Jdbi.java:341)
		at org.bmbgarage.dao.Database.connect(Database.java:20)
		at org.bmbgarage.servlet.LoginServlet.doPost(LoginServlet.java:30)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLException: ORA-01017: nombre de usuario/contraseña no válidos; conexión denegada

https://docs.oracle.com/error-help/db/ora-01017/
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:603)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:598)
		at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1795)
		at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:866)
		at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1102)
		at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:456)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:508)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTHWithO5Logon(T4CTTIoauthenticate.java:1676)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1421)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1368)
		at oracle.jdbc.driver.T4CConnection.authenticateWithPassword(T4CConnection.java:1805)
		at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1748)
		at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:960)
		at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1126)
		at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104)
		at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:825)
		at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:651)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at org.jdbi.v3.core.Jdbi.lambda$create$2(Jdbi.java:152)
		at org.jdbi.v3.core.Jdbi.open(Jdbi.java:319)
		... 26 more
17-May-2024 17:18:26.406 SEVERE [http-nio-8084-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet [org.bmbgarage.servlet.LoginServlet] lanzó excepción
	org.jdbi.v3.core.ConnectionException: java.sql.SQLException: ORA-01017: nombre de usuario/contraseña no válidos; conexión denegada

https://docs.oracle.com/error-help/db/ora-01017/
		at org.jdbi.v3.core.Jdbi.open(Jdbi.java:341)
		at org.bmbgarage.dao.Database.connect(Database.java:20)
		at org.bmbgarage.servlet.LoginServlet.doPost(LoginServlet.java:30)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLException: ORA-01017: nombre de usuario/contraseña no válidos; conexión denegada

https://docs.oracle.com/error-help/db/ora-01017/
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:603)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:598)
		at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1795)
		at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:866)
		at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1102)
		at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:456)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:508)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTHWithO5Logon(T4CTTIoauthenticate.java:1676)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1421)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1368)
		at oracle.jdbc.driver.T4CConnection.authenticateWithPassword(T4CConnection.java:1805)
		at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1748)
		at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:960)
		at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1126)
		at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104)
		at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:825)
		at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:651)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at org.jdbi.v3.core.Jdbi.lambda$create$2(Jdbi.java:152)
		at org.jdbi.v3.core.Jdbi.open(Jdbi.java:319)
		... 26 more
17-May-2024 17:18:26.407 SEVERE [http-nio-8084-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet [org.bmbgarage.servlet.LoginServlet] lanzó excepción
	org.jdbi.v3.core.ConnectionException: java.sql.SQLException: ORA-01017: nombre de usuario/contraseña no válidos; conexión denegada

https://docs.oracle.com/error-help/db/ora-01017/
		at org.jdbi.v3.core.Jdbi.open(Jdbi.java:341)
		at org.bmbgarage.dao.Database.connect(Database.java:20)
		at org.bmbgarage.servlet.LoginServlet.doPost(LoginServlet.java:30)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1623)
	Caused by: java.sql.SQLException: ORA-01017: nombre de usuario/contraseña no válidos; conexión denegada

https://docs.oracle.com/error-help/db/ora-01017/
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:603)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:598)
		at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1795)
		at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:866)
		at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1102)
		at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:456)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:508)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTHWithO5Logon(T4CTTIoauthenticate.java:1676)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1421)
		at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1368)
		at oracle.jdbc.driver.T4CConnection.authenticateWithPassword(T4CConnection.java:1805)
		at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1748)
		at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:960)
		at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1126)
		at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104)
		at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:825)
		at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:651)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at org.jdbi.v3.core.Jdbi.lambda$create$2(Jdbi.java:152)
		at org.jdbi.v3.core.Jdbi.open(Jdbi.java:319)
		... 26 more
